export default {
  documents: {
    'quick-start': './quick-start',
  },
  components: {
    Basic: {
      // layout: './layout',
      // color: './color',
      // typography: './typography',
      Icon: '../pages/icon',
      Button: '../pages/button',
    },
    Form: {
      // radio: './radio',
      Checkbox: '../pages/checkbox',
      Input: '../pages/input',
      // 'input-number': './input-number',
      Select: '../pages/select',
      // cascader: './cascader',
      // switch: './switch',
      // slider: './slider',
      // 'time-picker': './time-picker',
      // 'date-picker': './date-picker',
      // 'datetime-picker': './datetime-picker',
      // upload: './upload',
      // rate: './rate',
      // 'color-picker': './color-picker',
      // transfer: './transfer',
      // form: './form',
    },
    Data: {
      // table: './table',
      Tag: '../pages/tag',
      // progress: './progress',
      // tree: './tree',
      Pagination: '../pages/pagination',
      // badge: './badge',
    },
    Notice: {
      Alert: '../pages/alert',
      // loading: './loading',
      Message: '../pages/message',
      Modal: '../pages/modal',
      Confirm: '../pages/confirm',
    },
    Nav: {
      // menu: './menu',
      // tabs: './tabs',
      Breadcrumb: '../pages/breadcrumb',
      // dropdown: './dropdown',
      // steps: './steps',
    },
    Others: {
    //   dialog: './dialog',
    //   tooltip: './tooltip',
    //   popover: './popover',
    //   card: './card',
    //   carousel: './carousel',
    //   collapse: './collapse',
    },
  },
};
